### ISSUE TITLE
Support for different countries

### ISSUE THREAD

**Issue by 11digitlabs** [Mango-information-systems/twitto_be#116]
All country details should be done in a params file, making it easy to run separate instances of twitto per country

**Comment by 11digitlabs** [comment]
@mef could you please have a look? Checkout branch `issue-116-country-params-wip`
I believe I've moved all country related settings to params.json

Do not forget to copy from `params-sample.json`

What do you think?

**Comment by 11digitlabs** [comment]
We might need to setup different persist files for each country, so that we don't accidentally mess up.

**Comment by 11digitlabs** [comment]
Added some more parameters in json file and a sample-json for Greece

**Comment by mef** [comment]
Heads-up Panos, I've made a small change in params.json structure (cf previous commit) - branch 3.0.0-wip

**Comment by 11digitlabs** [comment]
@mef fixed 502 texts and merged with 3.0.0 Please check. Next task here is to camelcase all the params

**Comment by 11digitlabs** [comment]
Greece is working fine. I've also updated the json files
Moving it to please test

![image](https://cloud.githubusercontent.com/assets/2484390/19341516/57bea062-9136-11e6-8b76-acc6e8546040.png)

**Comment by mef** [comment]
Heads-up @11digitlabs 

All the geo-related settings have been moved in a separate file outside of params.json.

This is because this data is `require`-d inside client-side map.js view, and it was causing the twitter app keys to be leaked to the client.

Please have a look at the commit d1be7c3, you'll need to adapt files accordingly.
