### ISSUE TITLE
Browsersync setup

### ISSUE THREAD

**Issue by 11digitlabs** [Mango-information-systems/twitto_be#92]
Setup https://www.browsersync.io

**Comment by 11digitlabs** [comment]
@mef please do an `npm install`

When `npm start` it should open a browser window on port 3000. On my machine, I needed to have to wait to reload for 2 seconds, give it a try without on yours.

CSS are automatically injected, in case of JS the browser reloads.

You can have multiple browsers, resolutions, mobile, tablets listening to the port 3000 and all will be reloaded

**Comment by mef** [comment]
Feedback:

* nodemon and browsersync are conflicting, as bot of them restart the server on client files change.
* browsersync is setup to only watch client-side or view changes. Shouldn't it also listen to server-side changes?

Suggestion:
* remove nodemon
* setup browsersync so that it listens to all changes

Tested with nodemon removed, the reload is much faster in that configuration.

**Comment by 11digitlabs** [comment]
How did you remove nodemon? I tried with some configuration in order to point to app.js for the server but doesnt work

Right now, BS does not restart the server. Maybe with some gulp configuration we could do it, but still it would be two things. One to restart the server and one for the client (unless im very mistaken)

 Did you find anything online?

(no irony in the above message :P )

**Comment by mef** [comment]
No worry.

> How did you remove nodemon? 

Replace 

    "watch:server": "nodemon --ignore public/ app.js",

by 

    "watch:server": "node app.js",

> Oh, I didn't realize that, indeed, sorry.

> Maybe with some gulp configuration

No no no let's not involve gulp in here. 

Let's leave nodemon in place then.
